### PR TITLE
Typo fixes in mksitemap

### PR DESCRIPTION
**Pull request by xexyl**
'tarball' -> 'sitemap' (yank paste error?).

### CODE REVIEW

**Comment by lcn2** [comment]
Thank you kindly @xexyl

**Comment by lcn2** [comment]
There are about 100 GitHub repos, currently private and waiting for a files such as `LICENSE` and `README.md` to be written as well as for code review and cleanup.

These 100+ repos are the "developer's workbench" we have developed and carried around for decades from place to place.  They await after the time when IOCCC28 is judged and published to be worked on: and **will welcome review and editing by people such as yourself**, @xexyl.

The `mksitemap` was the basis for the simplified [bin/gen-sitemap.sh](https://github.com/ioccc-src/temp-test-ioccc/blob/master/bin/gen-sitemap.sh) code.  We decided to publish it as a by-product of our recent emergency infrastructure project.

**Comment by xexyl** [comment]
> Thank you kindly @xexyl

You are very welcome my friend!

**Comment by xexyl** [comment]
> There are about 100 GitHub repos, currently private and waiting for a files such as `LICENSE` and `README.md` to be written as well as for code review and cleanup.
> 
Plus some that are public .. mine for instance. :-) .. but I can't be bothered for now. Though I know I should.

But you have a lot of repos! I know one I was interested in but we'll see if you ever make it public.


> These 100+ repos are the "developer's workbench" we have developed and carried around for decades from place to place. They await after the time when IOCCC28 is judged and published to be worked on: and **will welcome review and editing by people such as yourself**, @xexyl.
> 

Nice! I will be happy to do that when you're ready. And that time is exciting. I'm really trying hard to get things in order for that too!

> The `mksitemap` was the basis for the simplified [bin/gen-sitemap.sh](https://github.com/ioccc-src/temp-test-ioccc/blob/master/bin/gen-sitemap.sh) code. We decided to publish it as a by-product of our recent emergency infrastructure project.

Ah I see. Funny thing is years ago I was pondering what to do about that for some of my [websites]. I never got to it. Maybe this will be useful in that: though it's hardly an important thing for me at this time. 

Hope the infrastructure situation is completely resolved for you very soon!

I hope to work on the other repo a bit more today but I will be away for a while likely.

**Comment by lcn2** [comment]
> > There are about 100 GitHub repos, currently private and waiting for a files such as `LICENSE` and `README.md` to be written as well as for code review and cleanup.
> 
> > 
> 
> Plus some that are public .. mine for instance. :-) .. but I can't be bothered for now. Though I know I should.

The concept of a Programers Workbench at Bell Labs (see [PWB UNIX](https://en.wikipedia.org/wiki/PWB/UNIX?wprov=sfti1) had a profound effect.  It is why we carry, to this day, a `~/bench` directory.  Within the PWB culture at Bell Labs was the notion that one carried your tools of the trade from job site to job site.  These 100+ repo are those tools.

Now a few are private and won't be released because they are too specialized for our needs to be generally useful: but the vast majority of them are to be made public.
 
> But you have a lot of repos! I know one I was interested in but we'll see if you ever make it public.

Which one?

> > These 100+ repos are the "developer's workbench" we have developed and carried around for decades from place to place. They await after the time when IOCCC28 is judged and published to be worked on: and **will welcome review and editing by people such as yourself**, @xexyl.
> 
> Nice! I will be happy to do that when you're ready. And that time is exciting. I'm really trying hard to get things in order for that too!

Thanks in advance as that will be helpful to many.

> > The `mksitemap` was the basis for the simplified [bin/gen-sitemap.sh](https://github.com/ioccc-src/temp-test-ioccc/blob/master/bin/gen-sitemap.sh) code. We decided to publish it as a by-product of our recent emergency infrastructure project.
> 
> Ah I see. Funny thing is years ago I was pondering what to do about that for some of my [websites]. I never got to it. Maybe this will be useful in that: though it's hardly an important thing for me at this time.
> 
> Hope the infrastructure situation is completely resolved for you very soon!

Thank you and best wishes.

**Comment by xexyl** [comment]
> > > There are about 100 GitHub repos, currently private and waiting for a files such as `LICENSE` and `README.md` to be written as well as for code review and cleanup.
> > 
> > 
> > > 
> > 
> > 
> > Plus some that are public .. mine for instance. :-) .. but I can't be bothered for now. Though I know I should.
> 
> The concept of a Programers Workbench at Bell Labs (see [PWB UNIX](https://en.wikipedia.org/wiki/PWB/UNIX?wprov=sfti1) had a profound effect. It is why we carry, to this day, a `~/bench` directory. Within the PWB culture at Bell Labs was the notion that one carried your tools of the trade from job site to job site. These 100+ repo are those tools.

So **THAT'S** what PWB UNIX is! I mean I could have looked it up but I never bothered. I don't know if it's the first time I saw reference to it but I do know I saw it in the [Unix Heritage Society](https://www.tuhs.org).

The idea makes sense though I just didn't know of the name. Many of my config files are in multiple systems actually.


> 
> Now a few are private and won't be released because they are too specialized for our needs to be generally useful: but the vast majority of them are to be made public.

That makes sense. I'd say most of my repos are private and not even on GitHub.

> 
> > But you have a lot of repos! I know one I was interested in but we'll see if you ever make it public.
> 
> Which one?
> 

I cannot remember but I think it had to do with `sed(1)`. I think it was with one of the issues in the mkiocccentry repo. You took care of the problem for reasons I am no longer clear about. But it might have been the temp-test-ioccc repo too. I would probably remember it if I saw the name.


> > > These 100+ repos are the "developer's workbench" we have developed and carried around for decades from place to place. They await after the time when IOCCC28 is judged and published to be worked on: and **will welcome review and editing by people such as yourself**, @xexyl.
> > 
> > 
> > Nice! I will be happy to do that when you're ready. And that time is exciting. I'm really trying hard to get things in order for that too!
> 
> Thanks in advance as that will be helpful to many.

I'm always happy to help!

> 
> > > The `mksitemap` was the basis for the simplified [bin/gen-sitemap.sh](https://github.com/ioccc-src/temp-test-ioccc/blob/master/bin/gen-sitemap.sh) code. We decided to publish it as a by-product of our recent emergency infrastructure project.
> > 
> > 
> > Ah I see. Funny thing is years ago I was pondering what to do about that for some of my [websites]. I never got to it. Maybe this will be useful in that: though it's hardly an important thing for me at this time.
> > Hope the infrastructure situation is completely resolved for you very soon!
> 
> Thank you and best wishes.

Thank you and you too!

**Comment by lcn2** [comment]
> I cannot remember but I think it had to do with sed(1). I think it was with one of the issues in the mkiocccentry repo. You took care of the problem for reasons I am no longer clear about. But it might have been the temp-test-ioccc repo too. I would probably remember it if I saw the name.

Perhaps `dss(1)` - double page suppression in `sed(1)` in only 37 bytes?

We won a Bell Labs reunion contest (back in 1987) by shaving the smallest sed script record by 2 bytes.  🤓

**Comment by xexyl** [comment]
> > I cannot remember but I think it had to do with sed(1). I think it was with one of the issues in the mkiocccentry repo. You took care of the problem for reasons I am no longer clear about. But it might have been the temp-test-ioccc repo too. I would probably remember it if I saw the name.
> 
> Perhaps `dss(1)` - double page suppression in `sed(1)` in only 37 bytes?
> 

That is almost certainly it. It rings a bell and the task does too. Yes .. I checked to be sure. That is indeed the one.

> We won a Bell Labs reunion contest by shaving the smallest seed record by 2 bytes. 🤓

Nice!

But I can only think of two kinds of seeds at this time. The kind that goes in the ground (not it I am sure .. just a crazy hunch of mine :-) ) and then seeds for pRNGs. I want to say more are lingering at the tip of my fingers but what they might be I do not know. right now But I guess it's something else (not one of the two) that I either am not thinking of or I am unaware of. Mind elaborating?

**Pull request merged**
